# Generated by Django 4.2.23 on 2025-08-26 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='publicaciones/'),
        ),
    ]
